name: monitoring_guard_frontend
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.0
  flutter_svg: ^2.0.9
  icons_plus: ^5.0.0
  nfc_manager: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loginassets/
    - assets/berandaassets/
    - assets/widgetsassets/
